config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show]
  
  resources :hotels do
    resources :reviews, except: [:show, :index]
  end

  root 'static_pages#home'
end

app/models/address.rb
# == Schema Information
#
# Table name: addresses
#
#  id         :integer          not null, primary key
#  country    :string
#  state      :string
#  city       :string
#  street     :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  hotel_id   :integer
#

class Address < ActiveRecord::Base
  belongs_to :hotel

  validates :country, presence: true, length: { in: 2..60 }
  validates :state,   presence: true, length: { in: 2..40 }
  validates :city,    presence: true, length: { in: 2..40 }
  validates :street,  presence: true, length: { in: 2..100 }

end

app/models/hotel.rb
# == Schema Information
#
# Table name: hotels
#
#  id                 :integer          not null, primary key
#  title              :string
#  breakfast_included :boolean
#  room_description   :text
#  room_price         :decimal(, )
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  user_id            :integer
#  image              :string
#  rating             :decimal(, )      default(0.0)
#

class Hotel < ActiveRecord::Base
  belongs_to :user
  has_one :address, dependent: :destroy
  has_many :reviews, dependent: :destroy
  mount_uploader :image, ImageUploader

  scope :higher_rating, -> { order(rating: :desc) }

  accepts_nested_attributes_for :address
  validates_associated :address
  validates :title,              presence: true, length: { in: 2..40 }
  validates :room_description,   presence: true, length: { in: 4..140 }
  validates :room_price,         presence: true, numericality: true

  def recalculate_rating
    if self.reviews.blank?
      self.rating = 0
    else
      self.rating = self.reviews.average(:rating).round(3)
    end
    self.save
  end

  def reviewed_by?( user )
    ! self.reviews.find_by_user_id(user.id).nil?
  end
end

app/models/review.rb
# == Schema Information
#
# Table name: reviews
#
#  id         :integer          not null, primary key
#  body       :text
#  rating     :integer
#  hotel_id   :integer
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Review < ActiveRecord::Base
  belongs_to :hotel
  belongs_to :user

  after_create :recalculate_hotel_rating
  after_update :recalculate_hotel_rating
  after_destroy :recalculate_hotel_rating

  default_scope -> { order(created_at: :desc) }

  validates :rating, presence: true, inclusion: { in: 1..5 }
  validates :body,   presence: true, length: { in: 4..200 }
  validates :hotel,  presence: true
  validates :user,  presence: true
  validates_uniqueness_of :hotel_id, scope: :user_id

  private
    def recalculate_hotel_rating
      self.hotel.recalculate_rating
    end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

class User < ActiveRecord::Base
  has_many :hotels, dependent: :destroy
  has_many :reviews, dependent: :destroy
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :find_hotel, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    @hotels = Hotel.higher_rating.paginate(page: params[:page], :per_page => 8)
  end

  def new
    @hotel = current_user.hotels.build
    @hotel.build_address
  end

  def create
    @hotel = current_user.hotels.build(hotel_params)

    if @hotel.save
      flash[:success] = "New hotel added successfully!"
      redirect_to hotel_path(@hotel)
    else
      render 'new'
    end
  end

  def edit
  end

  def show
  end

  def update
    if @hotel.update(hotel_params)
      flash[:success] = "Hotel updated successfully!"
      redirect_to hotel_path(@hotel)
    else
      render 'edit'
    end
  end

  def destroy
    if @hotel.destroy
      flash[:success] = "Hotel deleted successfully!"
      redirect_to hotels_path
    else
      redirect_to hotel_path(@hotel)
    end
  end

  private

    def hotel_params
      params.require(:hotel).permit(
                                    :title,
                                    :breakfast_included,
                                    :room_description,
                                    :room_price,
                                    :image,
                                    address_attributes: [
                                      :country,
                                      :state,
                                      :city,
                                      :street
                                      ]
                                    )
    end

    def find_hotel
      @hotel = Hotel.find(params[:id])
    end

    def correct_user
      @hotel = current_user.hotels.find_by(id: params[:id])
      redirect_to root_url if @hotel.nil?
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_hotel
  before_action :find_review, only: [:edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :hotel_reviewed, only: [:new, :create]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.hotel_id = @hotel.id
    @review.user_id = current_user.id

    if @review.save
      flash[:success] = "New review added successfully!"
      redirect_to hotel_path(@hotel)
    else
      render 'new'
    end
  end

  def edit
  end

  def destroy
    if @review.destroy
      flash[:success] = "Review deleted successfully!"
      redirect_to hotel_path(@hotel)
    else
      redirect_to hotel_path(@hotel)
    end
  end

  def update
    if @review.update(review_params)
      flash[:success] = "Review updated successfully!"
      redirect_to hotel_path(@hotel)
    else
      render 'edit'
    end
  end

  private

    def review_params
      params.require(:review).permit(:rating, :body)
    end

    def find_hotel
      @hotel = Hotel.find(params[:hotel_id])
    end

    def find_review
      @review = Review.find(params[:id])
    end

    def correct_user
      @review = current_user.reviews.find_by(id: params[:id])
      redirect_to root_url if @review.nil?
    end

    def hotel_reviewed
      redirect_to hotel_path(@hotel) if @hotel.reviewed_by?( current_user )
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @hotels = Hotel.higher_rating.first(5)
    @reviews = Review.all.first(5)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]
  before_action :correct_user, only: [:show]

  def show
  end

  private
    def correct_user
      if current_user != User.find_by(id: params[:id])
        redirect_to root_url
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/hotels/_form.html.haml
= simple_form_for @hotel, html: {multipart: true} do |f|
 
  = f.input :title, label: "Hotel name"
  = f.input :breakfast_included, inline_label: "Breakfast included"
  = f.input :room_description, label: "Room description"
  = f.input :room_price, label: "Price"
  = f.input :image, :as => :file

  = f.simple_fields_for :address do |a|
    = a.input :country, :as => :string
    = a.input :state
    = a.input :city
    = a.input :street
    = f.button :submit

app/views/hotels/_hotel.html.haml
%div{ :class => "col-md-#{current_page?(hotels_path) ? 3 : 12}" }
  .hotel-preview
    = link_to image_tag(hotel.image.url(:preview)), hotel_path(hotel)
    %p 
      = link_to hotel.title, hotel_path(hotel)
    %div.review-rating{"data-score" => "#{hotel.rating}"}

app/views/hotels/edit.html.haml
- provide(:title, "Edit hotel")

%h1 Edit Hotel

= render 'form'

app/views/hotels/index.html.haml
- provide(:title, "Hotels")

%h1.hotels-title All hotels
%hr/

.row
  = render @hotels

.row
  = will_paginate

app/views/hotels/new.html.haml
- provide(:title, "New Hotel")

%h1 Add new Hotel

= render 'form'

app/views/hotels/show.html.haml
- provide(:title, @hotel.title)

.row
  .col-md-4
    .hotel-view
      .hotel-top
        = image_tag @hotel.image.url(:preview), :class => "hotel-image"

        %h1= @hotel.title
        %div.average-rating{"data-score" => "#{@hotel.rating}"}
        %em= pluralize(@hotel.reviews.count, 'review')

      .table-responsive
        %table.table
          %tbody

            %tr
              %td
                %strong Breackfast:
              %td #{ @hotel.breakfast_included ? '' : 'not' }included

            %tr
              %td
                %strong Room description:
              %td= @hotel.room_description

            %tr
              %td
                %strong Room price:
              %td= @hotel.room_price

      %h2 Address
      .table-responsive
        %table.table
          %tbody

            %tr
              %td
                %strong Country:
              %td= @hotel.address.country

            %tr
              %td
                %strong State:
              %td= @hotel.address.state

            %tr
              %td
                %strong City:
              %td= @hotel.address.city

            %tr
              %td
                %strong Street:
              %td= @hotel.address.street

      -if user_signed_in?
        -if @hotel.user == current_user
          .controls
            .btn-group
              = link_to 'Edit hotel', edit_hotel_path(@hotel), :class => "btn btn-default"
              = link_to 'Delete hotel', hotel_path(@hotel), method: :delete, data: { confirm: "Are you sure?" },  :class => "btn btn-default"

  .col-md-8
    .row
      .col-md-12
        %h2 Reviews
        -if user_signed_in?
          -if ! @hotel.reviewed_by?(current_user)
            %div
              = link_to new_hotel_review_path(@hotel), :class => "btn btn-success" do
                %span.glyphicon.glyphicon-plus{"aria-hidden" => "true"}
                Add Review
    .row
      = render @hotel.reviews

app/views/layouts/_header.html.haml
%nav.navbar.navbar-inverse
  .container

    .navbar-header
      %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "Hotel Advisor", root_path, class: "navbar-brand"

    #navbar.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li
          = link_to hotels_path  do
            %span.glyphicon.glyphicon-home{"aria-hidden" => "true"}
            Hotels
        - if user_signed_in?
          %li
            = link_to new_hotel_path  do
              %span.glyphicon.glyphicon-plus{"aria-hidden" => "true"}
              Add hotel

      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li
            = link_to current_user do
              %span.glyphicon.glyphicon-user{"aria-hidden" => "true"}
              = current_user.email
          %li= link_to 'Logout', destroy_user_session_path, :method => :delete
        - else
          %li= link_to 'Sign up', new_user_registration_path
          %li= link_to 'Log in', new_user_session_path

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html

  %head
    %title HotelAdvisor | #{yield(:title)}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body

    = render 'layouts/header'

    .container
      - flash.each do |message_type, message|
        %div{ :class => "alert alert-#{message_type}", "role" => "alert" }
          = message
      = yield
      = render 'layouts/footer'

app/views/reviews/_form.html.haml
/ = simple_form_for([@hotel, @hotel.reviews.build]) do |f|
= simple_form_for ([@hotel, @review]) do |f|
  %div#rating-input{"data-score" => "#{@review.rating}"}
    %label Rating
  = f.input :body, label: "Comment"
  = f.button :submit

app/views/reviews/_review.html.haml
.col-md-12
  .review
    -if current_page?(root_url)
      %p Review by #{review.user.email} for #{link_to review.hotel.title, hotel_path(review.hotel)}
    -else
      %p Review by #{review.user.email}
    %div.review-rating{"data-score" => "#{review.rating}"}
    %p= review.body
    %p Written #{time_ago_in_words(review.updated_at)} ago

    -if user_signed_in?
      -if review.user == current_user
        .btn-group
          = link_to 'Edit', edit_hotel_review_path(review.hotel, review), :class => "btn btn-default"
          = link_to 'Delete', hotel_review_path(review.hotel, review), method: :delete, data: { confirm: "Are you sure?" },  :class => "btn btn-default"

app/views/reviews/edit.html.haml
%h1 Edit Review

= render "form"

app/views/reviews/new.html.haml
%h1 New Review

= render 'form'

app/views/static_pages/home.html.haml
- provide(:title, "Home page")



.row
  .col-md-3
    .row
      .col-md-12
        %h1 Top 5 hotels
      = render @hotels
  .col-md-9
    .row
      .col-md-12
        %h1 Last reviews
      = render @reviews

app/views/users/show.html.haml
- provide(:title, current_user.email)

%p= current_user.email

= link_to 'Edit profile', edit_user_registration_path